'use client';
import { useEffect, useState } from 'react';
import { proofProviders, providerLabel, type ValueProof } from '@/lib/value-proof';
import { sampleValueProof } from '@/lib/sample-value-proof';
import styles from './value-proof-board.module.css';
const date = (v:string) => new Intl.DateTimeFormat('ja-JP',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Tokyo'}).format(new Date(v));
const stateLabels: Record<string,string> = { won:'候補入りに変化',lost:'候補外に変化',unchanged:'変化なし',unavailable:'比較不可',baseline:'基準測定' };
const vote = (v:boolean|null) => v===null?'取得不足':v?'候補入り':'候補外';
export function ValueProofBoard({sample,token,revision}:{sample:boolean;token:string;revision:string}) {
  const [proof,setProof]=useState<ValueProof|null>(()=>sample?sampleValueProof():null);
  const [error,setError]=useState(''); const [attempt,setAttempt]=useState(0);
  const [visibleCount,setVisibleCount]=useState(12); const [sourceFilter,setSourceFilter]=useState('');
  const [tab,setTab]=useState('answers'); const [provider,setProvider]=useState('all'); const [state,setState]=useState('all'); const [query,setQuery]=useState('');
  useEffect(()=>{
    if(sample) return;
    const controller=new AbortController();
    fetch(`/api/watch/proof?token=${encodeURIComponent(token)}`,{cache:'no-store',signal:controller.signal}).then(async response=>{
      const data=await response.json(); if(!response.ok) throw new Error(data.error||'根拠を読み込めませんでした。');
      if(!controller.signal.aborted){setProof(data);setError('');}
    }).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'読み込みに失敗しました。');});
    return ()=>controller.abort();
  },[sample,token,revision,attempt]);
  if(!proof) return <section className={`shell ${styles.board}`} aria-label="成果と根拠"><h2>成果と根拠</h2>{error?<p role="alert">{error} <button onClick={()=>setAttempt(v=>v+1)}>再試行</button></p>:<p role="status">保存済みの回答と公開履歴を読み込んでいます。</p>}</section>;
  const rows=proof.rows.filter(r=>(provider==='all'||r.provider===provider)&&(state==='all'||r.state===state)&&r.prompt.toLowerCase().includes(query.toLowerCase())&&(!sourceFilter||r.afterAnswers.some(a=>a.sources.some(s=>s.url===sourceFilter))));
  const won=proof.rows.filter(r=>r.state==='won').length, lost=proof.rows.filter(r=>r.state==='lost').length;
  const comparable=proof.rows.filter(r=>r.comparable).length;
  const tabs=[['answers','相談ごとの結果'],['opportunities','強みと改善対象'],['sources','AIが使った情報'],['changes','Rovanが整備した内容'],['history','測定の推移']];
  const answerColumn=(answers:ValueProof['rows'][number]['afterAnswers'],heading:string)=><div><h3 className={styles.colHead}>{heading}</h3>{answers.length?answers.map((a,index)=><details open={index===0} key={a.id} className={styles.answer}><summary>{a.status==='success'?vote(a.included):'未取得'} · 回答{a.repetition} · {a.model}</summary><p>{a.completedAt?date(a.completedAt):'日時未記録'}</p><p><strong>候補：</strong>{a.candidates.join(' / ')||'候補名なし'}</p><pre>{a.text||'回答本文が保存されていません。'}</pre>{a.truncated?<p>長い回答のため先頭部分を表示しています。</p>:null}<ul>{a.sources.map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title||s.url}</a> <small>{s.kind==='answer'?'回答で引用':s.kind==='search'?'検索で取得':'区分未記録'}</small></li>)}</ul></details>):<p>回答がありません。</p>}</div>;
  return <section id="value-proof" className={`shell ${styles.board}`} aria-label="成果と根拠">
    <header className={styles.header}><div><p className={styles.eyebrow}>成果と根拠 {sample?' / 見本':''}</p><h2>御社について、何が変わったか。</h2><p>相談・回答・参照元・公開した変更を、自分で確かめられます。</p></div><div className={styles.exports}><a href={`/api/watch/proof?${sample?'sample=1':`token=${encodeURIComponent(token)}`}&format=csv`} download>比較表を保存（CSV）</a><a href={`/api/watch/proof?${sample?'sample=1':`token=${encodeURIComponent(token)}`}&format=report`} download>報告書を保存</a></div></header>
    {sample?<p className={styles.notice}>これは機能と読み方の見本です。実際の企業の成果・公開・引用を示すものではありません。</p>:null}
    {error?<p role="alert">最新の根拠を読み込めていません。{error}<button onClick={()=>setAttempt(v=>v+1)}>再試行</button></p>:null}
    <div className={styles.summary}><div><span>候補入りに変化</span><strong>{comparable?`${new Set(proof.rows.filter(r=>r.state==='won').map(r=>r.promptId)).size}問`:'比較待ち'}</strong><small>AI別{won}件 / 比較可能{comparable}件</small></div><div><span>候補外に変化</span><strong>{comparable?`${new Set(proof.rows.filter(r=>r.state==='lost').map(r=>r.promptId)).size}問`:'比較待ち'}</strong><small>AI別{lost}件 / 低下も同じ条件で表示</small></div><div><span>Rovanの公開変更</span><strong>{proof.changes.length}回</strong><small>保存された反映済みの履歴</small></div><div><span>公開ページの引用</span><strong>{proof.publishedCitations.length?'確認あり':'未確認'}</strong><small>検索収録・流入・売上とは別の指標</small></div></div>
    <p className={styles.caption}>{date(proof.baselineAt)} → {date(proof.measuredAt)}。Web検索付きAPIの固定質問による測定です。実際の利用者の会話や売上ではありません。質問・モデル・地域・言語・反復条件が揃う回答だけを比較します。</p>
    <nav className={styles.tabs} aria-label="根拠の表示切替">{tabs.map(([id,label])=><button type="button" key={id} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</nav>
    {tab==='answers'?<div>
      <div className={styles.filters}><label>相談を検索<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="地域・専門分野・相談内容" /></label><label>AI<select value={provider} onChange={e=>setProvider(e.target.value)}><option value="all">すべてのAI</option>{proofProviders.map(p=><option key={p} value={p}>{providerLabel[p]}</option>)}</select></label><label>変化<select value={state} onChange={e=>setState(e.target.value)}><option value="all">すべての結果</option>{Object.entries(stateLabels).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label></div>
      <p role="status">{Math.min(rows.length,visibleCount)} / {rows.length}件を表示。各行を開くと前後の回答と参照元を確認できます。</p>
      {sourceFilter?<p>参照元で絞り込み中：{sourceFilter} <button onClick={()=>setSourceFilter('')}>解除</button></p>:null}
      {rows.length?rows.slice(0,visibleCount).map(r=><details key={r.id} className={styles.row}><summary><span className={styles.provider}>{providerLabel[r.provider]}</span><strong>{r.prompt}</strong><span className={styles[r.state]||styles.neutral}>{stateLabels[r.state]}</span><span>{vote(r.before)} → {vote(r.after)}</span></summary><div className={styles.comparison}>{answerColumn(r.beforeAnswers,'基準の回答')}{answerColumn(r.afterAnswers,'今回の回答')}</div>{!r.comparable?<p className={styles.caption}>{r.state==='baseline'?'基準測定です。次の測定から比較します。':'取得不足または条件不一致のため、前後の増減として数えません。'}</p>:null}</details>):<p className={styles.empty}>この条件に合う相談はありません。検索や絞り込みを変更してください。</p>}{rows.length>visibleCount?<button onClick={()=>setVisibleCount(n=>n+12)}>さらに{Math.min(12,rows.length-visibleCount)}件を見る（全{rows.length}件）</button>:null}
    </div>:null}
    {tab==='opportunities'?<div><h3>御社の強みが、まだ候補入りにつながっていない相談。</h3><p>公開済みの原文と相談を照合しています。関連語があることと、相談の全条件に対応できることは別です。</p>{proof.opportunities.length?proof.opportunities.map(o=><article key={o.promptId} className={styles.change}><h4>{o.prompt}</h4><p>候補外：{o.excludedProviders.map(p=>providerLabel[p]).join(' / ')}</p>{o.facts.length?<><strong>公開情報に関連する根拠あり</strong>{o.facts.map((f,i)=><p key={i}>{f.value} {f.sourceUrl?<a href={f.sourceUrl} target="_blank" rel="noopener noreferrer">原典を確認 ↗</a>:null}</p>)}<p>掲載した根拠がAIの回答に引用されるか、次の測定で追います。</p></>:<p>{proof.profilePath?'公開情報から、この相談に関連する根拠をまだ照合できていません。新しい実績や対応条件を推測で足すことはありません。':'公開済みの根拠が紐づいていません。診断結果から公開内容を確認できます。'}</p>}<button onClick={()=>{setQuery(o.prompt);setState('all');setProvider('all');setSourceFilter('');setTab('answers');}}>候補になった他社と回答を見る</button></article>):<p className={styles.empty}>取得が揃った回答では、候補外の相談はありません。未取得の回答はこの判定に含めていません。</p>}</div>:null}
    {tab==='sources'?<div><h3>どの情報が、回答の参照元になったか。</h3><p>「回答で引用」と「検索で取得」を区別します。過去の記録で区分がないものは引用実績に数えません。件数は取得成功した回答単位です。</p>{proof.sources.length?proof.sources.map(s=><article key={s.url} className={styles.source}><div><a href={s.url} target="_blank" rel="noopener noreferrer">{s.url}</a><p>{s.owned?'自社サイト':'外部サイト'} · {s.providers.map(p=>providerLabel[p]).join(' / ')}</p></div><strong>回答で引用 {s.answerCount?`${s.answerCount}件`:s.unknownCount?'区分未記録':'0件'}<small>参照元に出現 {s.count}件 / {s.promptIds.length}問</small></strong><button onClick={()=>{setQuery('');setSourceFilter(s.url);setState('all');setProvider('all');setTab('answers');}}>関連する相談を見る</button></article>):<p className={styles.empty}>参照元はまだ保存されていません。</p>}<p className={styles.caption}>外部サイトに御社が載っているかは、この一覧だけでは分かりません。第三者への投稿・掲載依頼は自動では行いません。</p></div>:null}
    {tab==='changes'?<div><h3>整備した事実と、その後の確認。</h3><div className={styles.next}><strong>{proof.profilePath?'公開ページを確認できます':'この見守りに紐づく公開ページは未確認です'}</strong>{proof.profilePath?<a href={proof.profilePath} target="_blank" rel="noopener noreferrer">公開内容を開く ↗</a>:<p>診断結果から、掲載する事実と参照元を確認して公開できます。</p>}<p>{proof.automationEnabled?'同意済みの範囲で継続更新が有効です。':'継続更新は未確認または停止中です。下の公開管理で状態を確認できます。'}</p></div>{proof.changes.length?proof.changes.map(c=><article className={styles.change} key={c.id}><p>{date(c.executedAt)} · {c.stage==='measured'?'公開後の測定あり':c.stage==='waiting'?'次回測定待ち':c.stage==='unlinked'?'対象相談の記録なし':'比較条件が未成立'}</p><h4>{c.summary}</h4>{c.addedFacts.map((f,i)=><p key={`a${i}`} className={styles.won}>追加：{f.value} {f.sourceUrl?<a href={f.sourceUrl} target="_blank" rel="noopener noreferrer">原典 ↗</a>:null}</p>)}{c.removedFacts.map((f,i)=><p key={`r${i}`} className={styles.lost}>更新前：{f.value}</p>)}<p>関連する相談 {c.promptIds.length}問（文章中の語句による関連付け）</p>{c.comparisons.length?<p>同条件の相談×AI {c.comparisons.length}件で、候補入り {c.comparisons.filter(r=>r.before).length} → {c.comparisons.filter(r=>r.after).length}件。変更による因果効果は未検証です。</p>:null}</article>):<p className={styles.empty}>公開内容を変更した実行記録はまだありません。下書きや測定だけを「改善済み」とは数えません。</p>}<div className={styles.next}><h4>次に確認すること</h4><p>{!proof.profilePath?'まず原典付きの情報を公開し、AIが参照できる状態にします。':!proof.publishedCitations.length?'次の測定で、公開ページが回答に引用されるかを確認します。引用がない状態も記録します。':'公開ページの引用と、相談ごとの候補入りが継続するかを確認します。'}</p><p>{proof.nextRunAt?`次回予定：${date(proof.nextRunAt)}`:'自動測定は停止中です。'}</p></div></div>:null}
    {tab==='history'?<div><h3>単発の上昇だけで判断しない。</h3><p>各AIの反復回答の過半数で候補入りと判定。反復不足は成功分母に含めません。パネルやモデル変更をまたぐ増減は「相談ごとの結果」で比較可否を確認してください。</p><div className={styles.history}>{proof.trend.map((point,i)=><article key={`${point.measuredAt}-${i}`}><h4>{date(point.measuredAt)} · {point.panel==='core'?'固定50問':'短いパネル'}</h4>{point.providers.map(p=><div key={p.provider}><span>{providerLabel[p.provider]}</span><meter min={0} max={p.successful||1} value={p.included} aria-label={`${providerLabel[p.provider]} 候補入り ${p.included} / ${p.successful}`} /><strong>{p.included} / {p.successful}問</strong><small>予定{p.scheduled}問・未取得{Math.max(0,p.scheduled-p.successful)}問</small></div>)}</article>)}</div></div>:null}
  </section>;
}
