import type { PublicProfile } from "@/lib/types";

const SAMPLE_DATE = "2026-09-01T09:00:00.000Z";

type SampleInput = Pick<PublicProfile, "slug" | "brandName" | "targetUrl" | "market" | "summary" | "targetCustomers" | "useCases" | "facts"> & { sourceTitle?: string };

function makeSampleProfile(input: SampleInput): PublicProfile {
  const sourcePages = [{
    url: input.targetUrl,
    title: input.sourceTitle ?? `${input.brandName} 参照元（見本）`,
    description: "実在の事業者情報を示すものではない、画面確認用のサンプルデータです。",
  }];
  const structuredData = JSON.stringify({
    "@context": "https://schema.org",
    "@type": "Organization",
    name: input.brandName,
    url: input.targetUrl,
    description: input.summary,
    knowsAbout: [input.market],
    inLanguage: "ja-JP",
    additionalProperty: input.facts.map((fact) => ({
      "@type": "PropertyValue",
      name: fact.label,
      value: fact.value,
    })),
  }, null, 2);
  const json = JSON.stringify({
    recordVersion: "1",
    publisher: "Rovan",
    sample: true,
    subject: { name: input.brandName, sourceUrl: input.targetUrl },
    summary: input.summary,
    market: input.market,
    targetCustomers: input.targetCustomers,
    useCases: input.useCases,
    facts: input.facts,
    sourcePages,
    updatedAt: SAMPLE_DATE,
  }, null, 2);
  const markdown = [
    `# ${input.brandName} 公開情報参照ページ（見本）`,
    "",
    "> これは画面確認用のサンプルデータです。実在の企業情報・推薦結果ではありません。",
    "",
    "## 概要",
    "",
    input.summary,
    "",
    "## 分野",
    "",
    input.market,
    "",
    "## 対象のお客様",
    "",
    ...input.targetCustomers.map((customer) => `- ${customer}`),
    "",
    "## 利用例",
    "",
    ...input.useCases.map((useCase) => `- ${useCase}`),
    "",
    "## 公開されている情報",
    "",
    ...input.facts.map((fact) => `- **${fact.label}**: ${fact.value}`),
    "",
    "## 参照元",
    "",
    `- [${input.targetUrl}](${input.targetUrl})`,
    "",
  ].join("\n");

  return {
    id: `sample_${input.slug}`,
    slug: input.slug,
    status: "published",
    title: `${input.brandName} 公開情報参照ページ（見本）`,
    brandName: input.brandName,
    targetUrl: input.targetUrl,
    summary: input.summary,
    market: input.market,
    targetCustomers: input.targetCustomers,
    useCases: input.useCases,
    facts: input.facts,
    sourcePages,
    structuredData: `${structuredData}\n`,
    markdown,
    json: `${json}\n`,
    createdAt: SAMPLE_DATE,
    updatedAt: SAMPLE_DATE,
    expiresAt: "2027-09-01T09:00:00.000Z",
    publishedAt: SAMPLE_DATE,
  };
}

const SAMPLE_PROFILES: Record<string, PublicProfile> = {
  "aoba-souzoku": makeSampleProfile({
    slug: "aoba-souzoku",
    brandName: "あおば相続法務事務所",
    targetUrl: "https://aoba-souzoku.example/",
    market: "相続・遺産分割・事業承継の法務相談",
    summary: "仙台市・名取市で、相続登記と遺産分割の書類整理を扱う事務所です。遠方の家族もオンラインで同席でき、必要な資料と費用は初回の相談で確認します（見本）。",
    targetCustomers: ["相続や遺産分割について相談先を探している方"],
    useCases: ["相続に関する初回相談", "遺産分割に関する相談", "事業承継に関する相談"],
    facts: [
      { label: "分野", value: "相続・遺産分割・事業承継の法務相談", sourceUrl: "https://aoba-souzoku.example/" },
      { label: "対応地域", value: "宮城県仙台市・名取市。遠方の相続人はオンライン同席に対応", sourceUrl: "https://aoba-souzoku.example/" },
      { label: "初回相談", value: "初回相談60分無料。対面・オンラインとも予約制、相談枠は1日3組まで（見本）", sourceUrl: "https://aoba-souzoku.example/" },
      { label: "料金例", value: "相続登記は税込88,000円から。登録免許税・証明書取得費等の実費は別途。対象不動産と必要資料を確認して個別見積", sourceUrl: "https://aoba-souzoku.example/" },
      { label: "相談時間", value: "平日オンライン相談は20時まで。土曜は予約相談に対応（見本）", sourceUrl: "https://aoba-souzoku.example/" },
      { label: "期間例", value: "遺産分割書類整理は必要資料が揃ってから2〜4週間の想定。資料不足や関係者の確認状況で変動し、合意成立・登記完了の期限は保証しない（見本）", sourceUrl: "https://aoba-souzoku.example/" },
      { label: "相談範囲", value: "相続関係・財産資料の整理、手続きの進め方と見積の相談。紛争・税務・個別の法的判断は適切な専門家への確認が必要。資格・登録・解決実績を示すものではない", sourceUrl: "https://aoba-souzoku.example/" },
      { label: "掲載区分", value: "見本", sourceUrl: "https://aoba-souzoku.example/" },
    ],
  }),
  "aoba-cafe": makeSampleProfile({
    slug: "aoba-cafe",
    brandName: "青葉カフェ",
    targetUrl: "https://aoba-cafe.example/",
    market: "自家焙煎・スペシャリティ珈琲・スイーツ",
    summary: "仙台市青葉区の自家焙煎珈琲店です。読書や少人数の作業に使え、豆の持ち帰りもできます。浅煎りと中深煎りを選べます（見本）。",
    targetCustomers: ["作業や読書ができるカフェを探している方", "自家焙煎珈琲を楽しみたい方"],
    useCases: ["店内での作業・読書", "テイクアウト", "コーヒー豆の購入"],
    facts: [
      { label: "分野", value: "自家焙煎・スペシャリティ珈琲・スイーツ", sourceUrl: "https://aoba-cafe.example/" },
      { label: "地域・サービス", value: "宮城県仙台市青葉区を想定。店内提供・テイクアウト・自家焙煎豆の店頭販売（見本）", sourceUrl: "https://aoba-cafe.example/" },
      { label: "席数・設備", value: "24席（カウンター8席・テーブル16席）。電源はカウンター8席、Wi-Fiあり。混雑時の作業利用は90分まで（見本）", sourceUrl: "https://aoba-cafe.example/" },
      { label: "メニュー料金", value: "ハンドドリップ税込550円、カフェラテ税込620円、チーズケーキ税込480円", sourceUrl: "https://aoba-cafe.example/" },
      { label: "豆の販売", value: "ハウスブレンド200g・税込1,400円。豆のまま、または器具に合わせて挽いて販売（見本）", sourceUrl: "https://aoba-cafe.example/" },
      { label: "営業時間", value: "火〜日9:00〜18:00、月曜休み。ドリンク提供は注文から5〜10分が目安（見本）", sourceUrl: "https://aoba-cafe.example/" },
      { label: "掲載区分", value: "見本", sourceUrl: "https://aoba-cafe.example/" },
    ],
  }),
  "aoba-bakery": makeSampleProfile({
    slug: "aoba-bakery",
    brandName: "青葉ベーカリー",
    targetUrl: "https://instagram.example/aoba_bakery",
    sourceTitle: "Instagram @aoba_bakery（見本）",
    market: "天然酵母のパン・早朝営業のベーカリー",
    summary: "群馬県高崎市のパン屋です。ホームページはなく、Instagramで発信しています。自家製の天然酵母で焼く食パンとカンパーニュが中心です（見本）。",
    targetCustomers: ["出勤前に焼きたてのパンを買いたい方", "天然酵母のパンを探している方"],
    useCases: ["朝の通勤前の買い物", "予約での取り置き", "手土産用の焼き菓子"],
    facts: [
      { label: "得意なこと", value: "自家製の天然酵母で焼く食パン・カンパーニュ（見本）", sourceUrl: "https://instagram.example/aoba_bakery" },
      { label: "場所", value: "群馬県高崎市を想定。高崎駅から徒歩8分（見本）", sourceUrl: "https://instagram.example/aoba_bakery" },
      { label: "営業時間", value: "火〜土 7:00〜15:00、日月休み。売り切れ次第終了（見本）", sourceUrl: "https://instagram.example/aoba_bakery" },
      { label: "予約", value: "前日18時までInstagramのDMで取り置き可（見本）", sourceUrl: "https://instagram.example/aoba_bakery" },
      { label: "価格の例", value: "天然酵母食パン1斤 税込480円、カンパーニュ 税込620円（見本）", sourceUrl: "https://instagram.example/aoba_bakery" },
      { label: "掲載区分", value: "見本", sourceUrl: "https://instagram.example/aoba_bakery" },
    ],
  }),
  "yamada-bankin": makeSampleProfile({
    slug: "yamada-bankin",
    brandName: "山田板金製作所",
    targetUrl: "https://yamada-bankin.example/",
    market: "試作板金・精密金属加工",
    summary: "長野県松本市の板金製作所です。装置カバーや取付ブラケットの試作を、図面の確認から切断・曲げまで小ロットで受けています（見本）。",
    targetCustomers: ["小ロットの試作先を探している設計・開発担当者"],
    useCases: ["単品・小ロット試作", "3D CADデータを使った加工相談"],
    facts: [
      { label: "分野", value: "試作板金・精密金属加工", sourceUrl: "https://yamada-bankin.example/" },
      { label: "地域・配送", value: "長野県松本市・塩尻市の設計担当者向け。完成品は国内配送に対応、送料別途（見本）", sourceUrl: "https://yamada-bankin.example/" },
      { label: "ロット・材質", value: "1〜50個の試作ロット。鉄・ステンレス・アルミの板厚1.0〜3.0mm、展開寸法500×500mm以内を相談対象とする（見本）", sourceUrl: "https://yamada-bankin.example/" },
      { label: "入稿・加工", value: "STEP・DXF・PDF図面を受付。切断・曲げに対応し、公差・仕上げ・加工可否は図面ごとに確認（見本）", sourceUrl: "https://yamada-bankin.example/" },
      { label: "料金例", value: "鉄製L字ブラケット・板厚1.6mm・曲げ1か所の試作1個は税込8,800円から。材料・段取り込み、表面処理・送料別途", sourceUrl: "https://yamada-bankin.example/" },
      { label: "見積・納期", value: "図面受領後2営業日以内に見積回答、仕様確定後5〜10営業日で出荷する想定。材料在庫・数量・工程で変動（見本）", sourceUrl: "https://yamada-bankin.example/" },
      { label: "掲載区分", value: "見本", sourceUrl: "https://yamada-bankin.example/" },
    ],
  }),
  "azumino-sunshine": makeSampleProfile({
    slug: "azumino-sunshine",
    brandName: "安曇野サンシャイン果樹園",
    targetUrl: "https://azumino-sunshine.example/",
    market: "果樹栽培・産直ギフト",
    summary: "長野県安曇野市のりんご果樹園です。秋の収穫期に、家庭用と贈答用の箱を産地から届けます（見本）。",
    targetCustomers: ["産地からのギフトを探している方"],
    useCases: ["果物の産地直送", "贈答用ギフトの注文"],
    facts: [
      { label: "分野", value: "果樹栽培・産直ギフト", sourceUrl: "https://azumino-sunshine.example/" },
      { label: "地域・配送", value: "長野県安曇野市を想定。国内配送、離島など配送日数が長い地域は受付時に個別確認（見本）", sourceUrl: "https://azumino-sunshine.example/" },
      { label: "商品・料金", value: "家庭用りんご3kg箱・税込2,800円、贈答用3kg箱・税込3,800円。1箱8〜12玉が目安、送料は別途税込900円から", sourceUrl: "https://azumino-sunshine.example/" },
      { label: "収穫・品種", value: "9月下旬〜11月下旬の季節販売。シナノスイート・ふじを収穫時期に合わせて案内し、品種指定は在庫次第（見本）", sourceUrl: "https://azumino-sunshine.example/" },
      { label: "出荷目安・数量", value: "収穫期間中は注文確定から3〜5営業日で出荷、1日20箱までの想定。天候・収穫量で遅延や受付停止あり（見本）", sourceUrl: "https://azumino-sunshine.example/" },
      { label: "ギフト・品質", value: "贈答用は外観を選別し緩衝材入りで梱包。のし1枚に対応。糖度や蜜入りは保証せず、家庭用には小さな傷や色むらを含む（見本）", sourceUrl: "https://azumino-sunshine.example/" },
      { label: "掲載区分", value: "見本", sourceUrl: "https://azumino-sunshine.example/" },
    ],
  }),
  "nexora-cloud": makeSampleProfile({
    slug: "nexora-cloud",
    brandName: "Nexora Cloud",
    targetUrl: "https://nexora-cloud.example/",
    market: "法人向けクラウド業務支援",
    summary: "小規模な受託制作チーム向けに、案件・タスク・納期をまとめるクラウドサービスです。表計算で管理していた案件をCSVで取り込み、担当者ごとに進捗を共有できます（見本）。",
    targetCustomers: ["業務向けクラウドサービスを比較している法人担当者"],
    useCases: ["業務データの一元管理", "クラウドサービスの導入比較"],
    facts: [
      { label: "分野", value: "法人向けクラウド業務支援", sourceUrl: "https://nexora-cloud.example/" },
      { label: "対象地域・用途", value: "日本国内の5〜20名規模の制作・受託チーム向け。日本語で案件一覧・タスク割当・納期通知を利用（見本）", sourceUrl: "https://nexora-cloud.example/" },
      { label: "料金例", value: "基本プラン5ユーザーで月額税込9,800円、追加1ユーザー月額税込1,100円。10ユーザーなら月額税込15,300円。見本のNexora Cloud利用料でありRovanの料金ではない", sourceUrl: "https://nexora-cloud.example/" },
      { label: "容量・上限", value: "基本プランは1契約あたり進行中100案件・保存容量10GB。追加ユーザーで容量は増えない（見本）", sourceUrl: "https://nexora-cloud.example/" },
      { label: "試用・導入", value: "14日間の無料試用。CSV取込は1回1,000行まで、初期設定と取込確認は2〜3営業日を想定（見本）", sourceUrl: "https://nexora-cloud.example/" },
      { label: "サポート", value: "平日10:00〜17:00に日本語で受付、初回回答は2営業日以内が目安。個別開発・24時間対応は含まない（見本）", sourceUrl: "https://nexora-cloud.example/" },
      { label: "掲載区分", value: "見本", sourceUrl: "https://nexora-cloud.example/" },
    ],
  }),
};

export function getSampleProfile(slug: string) {
  return SAMPLE_PROFILES[slug] || null;
}
